# Model Context Protocol Configuration
# Configuration for the Claude Sonnet 4 + MCP Jira agent

# Client Configuration
client:
  model: "claude-3-5-sonnet-20241022"  # Latest Claude Sonnet model
  temperature: 0                       # Use 0 for consistent, factual responses
  max_tokens: 1024                     # Maximum tokens per response
  verbose: true                        # Enable detailed logging

# MCP Server Configuration  
mcp_server:
  name: "Jira MCP Server"
  description: "Jira integration via Model Context Protocol"
  transport: "stdio"                   # Communication transport
  
# Jira Configuration (loaded from .env)
jira:
  base_url: "${JIRA_API_BASE}"
  email: "${JIRA_EMAIL}"
  api_token: "${JIRA_API_TOKEN}"

# Available Tools
tools:
  - name: "get_my_jira_issues"
    description: "Get all issues assigned to current user"
    
  - name: "get_jira_issue_summary"  
    description: "Get summary of specific issue"
    parameters:
      - issue_key: "Jira issue key (e.g., KAN-1)"
      
  - name: "get_jira_issue_description"
    description: "Get detailed description of specific issue"
    parameters:
      - issue_key: "Jira issue key (e.g., KAN-1)"
      
  - name: "get_jira_issue_full_details"
    description: "Get complete details of specific issue"
    parameters:
      - issue_key: "Jira issue key (e.g., KAN-1)"

# Available Resources
resources:
  - uri: "jira://issues/my"
    description: "All issues assigned to current user"
    
  - uri: "jira://issue/{issue_key}"
    description: "Details for specific issue"

# Available Prompts
prompts:
  - name: "analyze_jira_issue"
    description: "Generate analysis prompt for Jira issue"
    parameters:
      - issue_key: "Issue to analyze"
      - analysis_type: "Type of analysis (summary, detailed, actionable)"
